### ISSUE TITLE
[Bug]: No keyboard/mouse input in Sunshine

### ISSUE THREAD

**Issue by miguelangel-nubla** [Steam-Headless/docker-steam-headless#107]
### Describe the Bug

Keyboard/mouse not working when connected with Moonlight to the Sunshine server.

Tracked it down to udevd daemon not running, it was a pain to debug.

Workaround:
1. `sudo /lib/systemd/systemd-udevd --daemon`
2. Restart sunshine.

I am unable to reproduce it on another system, and can't find a error anywhere on the logs. As far as I know it is completely silent except it is obviously not running `px aux | grep udevd`

This compounds with the fact that udev supervisor unit watches for the PID of [udevadm monitor](https://github.com/Steam-Headless/docker-steam-headless/blame/master/overlay/usr/bin/start-udev.sh) instead of udevd daemon. Maybe creating a exclusive udevd supervisor unit helps?

Regardless, I understand supervisord does not have dependency management. Given the nature of this container it looks like issues like this are going to get worse.

Would migrating to an alternative with support for dependencies such as S6-overlay make sense in the bigger picture? I don't know which path should I take to submit a PR.

### Version

Build: [2023-11-18 02:38:41] [master] [6cc9f56155f3c7f9fc6bc9c22ef2cbf555029c00] [debian]

### Platform

Distribution: Running under systemd-nspawn with [jlmkr ](https://github.com/Jip-Hop/jailmaker) on TrueNAS Scale
Linux Kernel: 5.15.131+truenas
GPU Driver versions: | NVIDIA-SMI 515.65.01    Driver Version: 515.65.01    CUDA Version: 11.7     |
Docker: 24.0.7, build afdd53b
Docker-compose: v2.21.0

**Comment by janlothar** [comment]
Thank you for your service @miguelangel-nubla. Your quick fix solved the same issue I had. Would be nice if we could get an official fix for this though.

**Comment by janlothar** [comment]
on further use I realize that the workaround suggested only allows mouse input, but not keyboard

**Comment by armouredking** [comment]
Can confirm, this workaround allowed me to use my input devices with the Docker. OS Unraid 6.12.8

**Comment by DCCInterstellar** [comment]
I've been running into this same exact issue on Unraid 6.12.0 with Docker. Currently using the latest patch for josh5/steam-headless. 

1. sudo /lib/systemd/systemd-udevd --daemon
2. Restart sunshine.

The command that was mentioned resolved this issue and is now working. Thank you so much! I'm going to save that command for future use just incase it acts up again.

**Comment by leinaht** [comment]
Having the same issue but on Proxmox rather than unRaid, but the fix isn't working for me. Setup is Proxmox > debian LXC with /dev/uinput mounted > docker compose. Steam remote play and VNC work fine, but when connecting via Moonlight/Sunshine I get no response from keyboard or mouse. I can also see that the udevd daemon isn't running at first but even manually starting it with the above command and restarting Sunshine doesn't help.

**Comment by reply-nick** [comment]
@leinaht adding this to your config should fix it 
```
lxc.cgroup2.devices.allow: c 13:* rwm
lxc.mount.entry: /dev/input dev/input none bind,optional,create=dir
lxc.hook.pre-start: sh -c "chown 100000:111000 /dev/input"
```
but `sudo /lib/systemd/systemd-udevd --daemon` and **sunshine** restart is still required.

**Comment by iksaku** [comment]
Just like last comment, I also created a custom script for this, but instead placed the script in the [Additional Software](https://github.com/Steam-Headless/docker-steam-headless?tab=readme-ov-file#additional-software) directory:

```sh
cat <<EOF > /opt/container-data/steam-headless/home/init.d/launch-systemd-udevd.sh
#!/usr/bin/env sh

echo "\e[36m  - Ensure 'systemd-udevd' is running...\e[0m"
sudo /lib/systemd/systemd-udevd --daemon >/dev/null 2>&1
EOF
```

> [!TIP]
> [Container's Entrypoint](https://github.com/Steam-Headless/docker-steam-headless/blob/6db83d2a22057ebf41994c37894c836769d11cfe/overlay/entrypoint.sh#L69-L73) makes sure that scripts in this directory are executable, so no need to do that on our side.

> [!IMPORTANT]
> Sunshine is started by supervisord, which [is launched after custom scripts](https://github.com/Steam-Headless/docker-steam-headless/blob/6db83d2a22057ebf41994c37894c836769d11cfe/overlay/entrypoint.sh#L88). We don't need to "restart" Sunshine.

**Comment by Tomasinjo** [comment]
~~This workaround doesn't work anymore for me after updating to latest debian image (tag debian).~~

EDIT: Accidentally removed "devices"  section from compose. Now it works even without workaround!!

**Comment by LATINO-BICEPS** [comment]
@reply-nick Hey, sorry for the the necro, but I'm trying to get this exact setup going with this image running in an LXC on Proxmox but I'm wondering why we need to do this:

>lxc.mount.entry: /dev/input dev/input none bind,optional,create=dir
lxc.hook.pre-start: sh -c "chown 100000:111000 /dev/input"

Specifically why `chown 100000:111000 /dev/input`? What is this seemingly arbitrary number corresponding to? I assume this should correspond to the GID of `input` which for me is 996 on the LXC and 997 on the host. However, the default permissions on `/dev/input` on my Proxmox 9 install are already owned by root:root so shouldn't it be `chown 100000:100000`?

```sh
root@pve:~# ls -l /dev/ | grep input
drwxr-xr-x  3 root root           500 Dec 24 10:01 input
```

Alternatively.. should it be `chown -R 100000:100997 /dev/input/event*` in my instance (input group is 996 on LXC)? 

EDIT: Figured it out, in my case it is `chown 100000:100996 /dev/input` then everything just works with the init script.

**Comment by ndom91** [comment]
Amazing, I felt like I tried everything and systemd-udevd init.d script finally fixed it for me!

**Comment by Menecats** [comment]
I've managed to automate the fix of automating the startup of the udevd daemon by creating a custom docker image with a cont-init.d script:

`<composition-folder>/docker-compose.yml`
```yaml
[...]

 steam-headless:
    #image: josh5/steam-headless:latest
    build: ./build

[...]
```

`<composition-folder>/build/Dockerfile`
```Dockerfile
FROM josh5/steam-headless:latest
COPY 85-enable-sunshine-input.sh /etc/cont-init.d/85-enable-sunshine-input.sh
```

`<composition-folder>/build/85-enable-sunshine-input.sh`
```bash
print_header "Enabling udevd daemon"

sudo /lib/systemd/systemd-udevd --daemon
print_step_header "udevd daemon enabled"

echo -e "\e[34mDONE\e[0m"
```

**Comment by jr551** [comment]
I hit a related but more specific variant of this on a live Proxmox setup and wanted to add concrete data because it took a while to isolate.

Environment:

- Proxmox VE LXC (`CT 102`)
- Debian 12 LXC
- Docker inside LXC
- `josh5/steam-headless:latest`
- Sunshine + Moonlight
- AMD iGPU exposed to the LXC

Observed behavior:

- Video over Moonlight worked
- Keyboard and mouse did not work at all
- This was reproduced and debugged live on the running container

What made this case different from the original report:

- `systemd-udevd` was running inside the container
- Sunshine was creating the virtual devices
- `/proc/bus/input/devices` and `udevadm info --export-db` both showed:
  - `Mouse passthrough`
  - `Mouse passthrough (absolute)`
  - `Keyboard passthrough`
- But Xorg initially failed with:

```text
Unable to open evdev device "/dev/input/event15" (No such file or directory)
```

Root cause in this setup:

- Inside the Docker container, `/dev` is a private tmpfs
- `/sys/class/input/*` and `/proc/bus/input/devices` knew about Sunshine's virtual devices
- But `/dev/input/event*` nodes were not being materialized inside the container
- So Xorg saw the hotplug event but the backing `/dev/input/event*` node did not exist yet

After I manually created the missing device nodes from `/sys/class/input/*/dev` and restarted Xorg, the Xorg log changed from:

```text
Unable to open evdev device "/dev/input/event15" (No such file or directory)
```

to successful device attachment, for example:

```text
XINPUT: Adding extended input device "Mouse passthrough" (type: MOUSE, id 7)
XINPUT: Adding extended input device "Keyboard passthrough" (type: KEYBOARD, id 8)
```

The exact live-tested workaround that got input attaching in this Docker-in-LXC case was:

1. Ensure the outer LXC allows Linux input devices (`c 13:* rwm`), otherwise you can hit permission problems later.
2. Run a real `systemd-udevd`.
3. Create `/dev/input/*` nodes inside the container from `/sys/class/input/*/dev` when they are missing.
4. Restart or re-enumerate Xorg after Sunshine creates the virtual devices.

In my case, the most important missing piece was not just "udevd must be running", but:

> Sunshine virtual input devices can exist in sysfs without corresponding `/dev/input/event*` nodes existing inside the container.

That seems worth handling directly in the image when running with a private `/dev`, or at least documenting for Docker-in-LXC / nspawn / jail-style environments.

If useful, I can turn the workaround into a PR. The minimal behavior change would be:

- detect missing `/dev/input/*` nodes for devices already visible in `/sys/class/input`
- create them
- restart or force Xorg to re-enumerate once Sunshine virtual devices appear

**Comment by andreasntr** [comment]
_For those who come after_ this is the complete setup which allowed me to make passthrough work

#### Setup
- proxmox
- debian 13 LXC privileged
- docker compose

#### LXC config
```
arch: amd64
cores: 2
dev0: /dev/dri/renderD129
dev1: /dev/dri/card0
dev2: /dev/uinput
features: fuse=1,nesting=1
hostname: games
memory: 4096
net0: name=eth0,bridge=vmbr0,firewall=1,hwaddr=BC:24:11:A4:E3:4A,ip=dhcp,ip6=dhcp,type=veth
ostype: debian
rootfs: local-lvm:vm-103-disk-0,size=15G
swap: 1024
timezone: Europe/Rome
lxc.cgroup2.devices.allow: c 13:* rwm
######################################### 
TRY WITHOUT THESE FIRST
#########################################
lxc.mount.entry%3A /dev/input dev/input none bind,optional,create=dir
lxc.hook.pre-start%3A sh -c "chown 100000:100996 /dev/input"
# 996 is the id of my input group (cat /etc/group | grep input)
```

#### docker-compose.yaml
```yaml
services:
  steam-headless:
    container_name: steam-headless
    #image: ghcr.io/steam-headless/steam-headless:stable
    build:
      dockerfile_inline: |
        FROM ghcr.io/steam-headless/steam-headless:stable
        COPY ./fix-inputs.sh /etc/cont-init.d/85-enable-sunshine-input.sh
    pull_policy: build
    restart: on-failure
    shm_size: ${SHM_SIZE}
    ipc: host # Could also be set to 'shareable'
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    # NETWORK:
    ## NOTE:  With this configuration, if we do not use the host network, then physical device in>
    ##        is not possible and your USB connected controllers will not work in steam games.
    network_mode: host
    hostname: ${NAME}
    extra_hosts:
      - "${NAME}:127.0.0.1"

    # ENVIRONMENT:
    ## Read all config variables from the .env file
    environment:
      # System
      - TZ=${TZ}
      - USER_LOCALES=${USER_LOCALES}
      - DISPLAY=${DISPLAY}
      # User
      - PUID=${PUID}
      - PGID=${PGID}
      - UMASK=${UMASK}
      - USER_PASSWORD=${USER_PASSWORD}
      # Mode
      - MODE=${MODE}
      # Web UI
      - WEB_UI_MODE=${WEB_UI_MODE}
      - ENABLE_VNC_AUDIO=${ENABLE_VNC_AUDIO}
      - PORT_NOVNC_WEB=${PORT_NOVNC_WEB}
      - NEKO_NAT1TO1=${NEKO_NAT1TO1}
      # Steam
      - ENABLE_STEAM=${ENABLE_STEAM}
      - STEAM_ARGS=${STEAM_ARGS}
      # Sunshine
      - ENABLE_SUNSHINE=${ENABLE_SUNSHINE}
      - SUNSHINE_USER=${SUNSHINE_USER}
      - SUNSHINE_PASS=${SUNSHINE_PASS}
      # Xorg
      - ENABLE_EVDEV_INPUTS=${ENABLE_EVDEV_INPUTS}
      - FORCE_X11_DUMMY_CONFIG=${FORCE_X11_DUMMY_CONFIG}
      # Nvidia specific config
      - NVIDIA_DRIVER_CAPABILITIES=${NVIDIA_DRIVER_CAPABILITIES}
      - NVIDIA_VISIBLE_DEVICES=${NVIDIA_VISIBLE_DEVICES}
      - NVIDIA_DRIVER_VERSION=${NVIDIA_DRIVER_VERSION}

    # DEVICES:
    devices:
      # Use the host fuse device [REQUIRED].
      - /dev/fuse
      # Add the host uinput device [REQUIRED].
      - /dev/uinput
      # Add AMD/Intel HW accelerated video encoding/decoding devices [REQUIRED].
      # NOTE: See documentation for determining which devices to configure here if you have multi>
      - /dev/dri/card0
      - /dev/dri/renderD129
    # Ensure container access to devices 13:*
    device_cgroup_rules:
      - 'c 13:* rmw'

    # VOLUMES:
    volumes:
      # The location of your home directory.
      - ${HOME_DIR}/:/home/default/:rw

      # The location where all games should be installed.
      # This path needs to be set as a library path in Steam after logging in.
      # Otherwise, Steam will store games in the home directory above.
      - ${GAMES_DIR}/:/mnt/games/:rw

      # The Xorg socket.
      - ${SHARED_SOCKETS_DIR}/.X11-unix/:/tmp/.X11-unix/:rw

      # Pulse audio socket.
      - ${SHARED_SOCKETS_DIR}/pulse/:/tmp/pulse/:rw
```

#### .env
```
NAME=SteamHeadless
TZ=Europe/Rome
USER_LOCALES=it_IT.UTF-8 UTF-8
DISPLAY=:55
SHM_SIZE=2G
HOME_DIR=/var/docker/steam-headless/home
SHARED_SOCKETS_DIR=/var/docker/steam-headless/sockets
GAMES_DIR=/var/docker/steam-headless/games
PUID=1000
PGID=1000
UMASK=022
USER_PASSWORD=<redacted>
MODE=primary
WEB_UI_MODE=vnc
ENABLE_VNC_AUDIO=false
PORT_NOVNC_WEB=8083
NEKO_NAT1TO1=
ENABLE_STEAM=true
STEAM_ARGS=-silent
ENABLE_SUNSHINE=true
SUNSHINE_USER=admin
SUNSHINE_PASS=<redacted>
ENABLE_EVDEV_INPUTS=true
FORCE_X11_DUMMY_CONFIG=true
NVIDIA_DRIVER_CAPABILITIES=all
NVIDIA_VISIBLE_DEVICES=all
NVIDIA_DRIVER_VERSION=
```

#### fix-inputs.sh
```sh
#!/usr/bin/env sh

print_header "Enabling udevd daemon"

sudo /lib/systemd/systemd-udevd --daemon
print_step_header "udevd daemon enabled"

echo -e "\e[34mDONE\e[0m"
```

Also check #218 for steam installer not starting

Huge thanks to all the suggestions in this issue
