### ISSUE TITLE
Unclear if supports AMD Radeon GPU

### ISSUE THREAD

**Issue by Kreakdude** [Steam-Headless/docker-steam-headless#145]
### Description

The readme under features says NVIDIA, AMD and Intel gpus are supported, but in the releases it just says Nvidia. Also I'm trying to use the docker compose and there's no instructions on how to configure it so it uses AMD. It seems to only support NVIDIA because of all the NVIDIA named vars like device_ids: ["${NVIDIA_VISIBLE_DEVICES}"]. So how would I change the docker compose for my Radeon GPU?

**Comment by cRaZy-bisCuiT** [comment]
Hi @Kreakdude,
do you have a display attached to your host running Docker? This could already solve the problem maybe.

The Container runs on AMDGPU. I tried it on an integrated 5750GE APU (Host is Debian, Proxmox host) as well as a RX 6800 on Arch Linux Host (Sway WM). Both are working fine.

I could check my config when I'm back at home if you wish.

**Comment by Josh5** [comment]
AMD and Intel GPUs don't need all the bullocks that NVIDIA GPUs do. NVIDIA has all the joy of proprietary Linux drivers and custom X display configuration.
So long as your host is set up with the required drivers, the container should "just work" with your AMD GPU.
As mentioned above, if you are having issues, it may be that you need to invest in an HDMI EDID emulator (only about $5) that will simulate a monitor plugged in. Other issues could be caused by having multiple GPUs.

**Comment by Kreakdude** [comment]
No, @cRaZy-bisCuiT I do not have a display attached. It's on a dedicated server I recently bought.

My current issue is an error saying /dev/fuse/ doesn't exist which I checked and it doesn't. I'm not sure what it is or how to get it. I'm guessing I'll get the same problem with /dev/uinput/. I don't see anything about them in the setup so there's some more room for improvement on the documentation.

Before I get farther though, I wanted to make sure I wasn't wasting my time trying to get a Radeon GPU to work with this docker image in this repo. Which it sounds like it's supposed to support AMD so I'm not wasting my time.

**Comment by cRaZy-bisCuiT** [comment]
I use the following ENVs with Docker Compose and that works pretty well for me:
```
---
services:
  steam-headless:
    image: josh5/steam-headless:debian
    restart: unless-stopped
    runtime: ${DOCKER_RUNTIME}
    shm_size: ${SHM_SIZE}
    ipc: host # Could also be set to 'shareable'
    privileged: true
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined

    # NETWORK:
    network_mode: host
    hostname: ${NAME}
    extra_hosts:
      - "${NAME}:127.0.0.1"
    
    # ENVIRONMENT:
    ## Read all config variables from the .env file
    env_file: .env

    # DEVICES:
    devices:
      # Use the host fuse device.
      - /dev/fuse
      # Add the host uinput device.
      - /dev/uinput
      # Add AMD/Intel HW accelerated video encoding/decoding devices (optional)
      - /dev/dri/D128
      - dev/dri/card1
    # Ensure container access to devices 13:*
    device_cgroup_rules:
      - 'c 13:* rmw'

    # VOLUMES:
    volumes:
      # The location of your home directory.
      - /opt/container-data/steam-headless/home/:/home/default/:rw

      # The location where all games should be installed.
      # This path needs to be set as a library path in Steam after logging in.
      # Otherwise, Steam will store games in the home directory above.
      - /mnt/games/:/mnt/games/:rw

      # The Xorg socket. This will be shared with other containers so they can access the X server.
      # Select only one option or leave commented out to not share the Xorg socket with any other Docker containers.
      #   Option #1) Start a X server in the container to share with any other containers.
      #- /opt/container-data/steam-headless/.X11-unix/:/tmp/.X11-unix/:rw
      #   Option #2) Use an existing X server running on the host.
      #- /tmp/.X11-unix/:/tmp/.X11-unix/:rw

      # Pulse audio socket. This will be shared with other containers so they can access the audio sink.
      # Leave commented out to not share the pulse socket with any other Docker containers.
      #- /opt/container-data/steam-headless/pulse/:/tmp/pulse/:rw
```
You have to make sure fuse is working for you on the host. I would have to search my history to find those settings but a google search might help here as well.

As stated by @Josh5 and me: You most likely need display connected to your server host HDMI port or a HDMI EDID emulator. I had the same problem. I did not work until I connected something to the HDMI port of the hosts GPU.
